# https://github.com/marketplace/actions/upload-s3
name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - pipeline-*
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: import secrets
        run: |
          echo "${{ secrets.SECRET_PROPERTIES }}" >> secrets.properties
          cat secrets.properties
          mv secrets.properties ./ApplicationModule/src/main/resources

      - name: run tests
        run: |
          mvn clean test

      - name: generate jars
        run: |
          mvn clean package
      
      - name: create dist folder
        run: |
          ls
          mkdir dst
          find . -name \*.jar -exec cp {} dst/ \;
          ls

      - name: Create Docker image
        run: |
          docker build -t bmg-backend .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2

      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 763752984178.dkr.ecr.us-west-2.amazonaws.com
          docker tag bmg-backend:latest 763752984178.dkr.ecr.us-west-2.amazonaws.com/bmg-backend:latest
          docker push 763752984178.dkr.ecr.us-west-2.amazonaws.com/bmg-backend:latest
 